### ISSUE TITLE
Linux UI not Updated

### ISSUE THREAD

**Issue by nshmadhani** [klaussinani/ao#131] opened 2020-03-05 14:22 UTC
**Describe the bug**
After Installing the Ao app using snap, the UI i get is not the same as the UI shown in readme

![Screenshot from 2020-03-05 19-49-20](https://user-images.githubusercontent.com/17786740/75990319-bfcea200-5f1a-11ea-8b9e-a62b8bb18b60.png)

 - OS:Ubuntu 19.04
 - Ao Version: 6.9.0

**Comment by GoodThiefGolgotha** [comment] 2020-03-27 20:10
I have the same problem.

- Zorin OS 15.2
- AO version 6.9.0

**Comment by Trits** [comment] 2020-03-28 10:26
Can confirm on Ubuntu 19.10, AO 6.9.0, installed through snap.

**Comment by ctesiphon** [comment] 2020-03-29 14:06
@nshmadhani :

This is a due to the way that Ao is designed : some of the elements are not part of the actual app ; they are loaded from the Microsoft Todo web-app.

Please consider closing this issue, since it is not a bug.

**Closed** 2020-04-01 10:15 UTC
